package com.model.pojos;
// Generated 6/12/2017 01:34:10 AM by Hibernate Tools 4.3.1



/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private Integer codigo;
     private Categoria categoria;
     private String titulo;
     private String autor;
     private int anio;

    public Libro() {
    }

    public Libro(Categoria categoria, String titulo, String autor, int anio) {
       this.categoria = categoria;
       this.titulo = titulo;
       this.autor = autor;
       this.anio = anio;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }




}


